module.exports = {
  SAVE_ORDER: "Order submitted successfully",
  insufficient_balance: "You have insufficient balance. Please make recharge",
  my_profile: "My profile",
  MY_ORDERS: "My orders",
  PAYMENT_SUCCESS: "Payment created successfully",
  GET_RECHARGE: "Your recharge list",
  ADD_RECHARGE: "Your recharge req submitted successfully",
  ADD_BANK_CARD: "Your bank card save successfully",
  UPDATE_BANK_CARD: "Your bank card updated successfully",
  UNABLE_BANK_CARD: "We are unable to update your bank account",
  GET_BANK_CARD: "Your bank card list",
  GET_BANK_CARD_ID: "Your bank card detail",
  BANK_CARD_EXIT: "This bank account are already linked to another account",
  INVALID_OTP: "This is invalid otp",
  MOBILE_IS_USE: "This mobile is already use",
  SEND_OTP_MESSAGE: "Use 123456 now for verification code",
  ADD_WITHDRAW_REQUEST: "Your Withdraw req submitted successfully",
  WITHDRAW_REQUEST_FIRST: "Your Withdrawal request not submitted unless you do not make a recharge",
  WITHDRAW_REQUEST_AMMOUNT: "You have insufficient balance in your wallet",
  GET_WITHDRAW_REQUEST: "Your Withdraw req get successfully",
  STATUS_UPDATE_SUCCESSFULLY: "Status updated successfully",
};
